### PR TITLE
Fixing color code

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by egoist** [comment]
hmm you don't like the current color?

**Comment by spekulatius** [comment]
It's more about the length. Hex colors are 6 chars, this is eight.

**Comment by egoist** [comment]
This is a valid format: https://caniuse.com/#feat=css-rrggbbaa

But it seems IE doesn't support this, we may switch to rgb instead.

**Comment by spekulatius** [comment]
Ohhhh, that's new for me 😅️ Thanks for sharing the link 🙏️

**Pull request merged**
